### ISSUE TITLE
Add Kepler Helm Chart to ArtifactHub

### ISSUE THREAD

**Issue by bradmccoydev** [sustainable-computing-io/kepler-helm-chart#20]
Now that we are hosting and indexing the helm chart for this repo on GitHub Pages from the work done in https://github.com/sustainable-computing-io/kepler-helm-chart/issues/7 we can now create an entry in ArtifactHub that will point people to this and show the versions including default latest version.

This is important for the adoption of Kepler, as ArtifactHub is the go-to for when folks want to search for new projects and they like ArtifactHub as it can help them to try charts faster without the hassle of forking repos then manually installing charts etc.

The following tasks are required for us to 'host' on ArtifactHub:
## ✅ Tasks
- [x] Add New Org on ArtifactHub for sustainable-computing-io
- [x] Add new repo on ArtifactHub for Kepler under the new org
- [x] Associate new repo with new Org
- [x] Add README.md to helm charts adding possible values for the chart
- [x] Add meta data to this repo for artifact keywords etc
- [x] Get the link for the URL of the Kepler logo that won't be deleted for ArtifactHub
- [x] Add a badge to this repo for a link to ArtifactHub
- [x] Add signed, and verified badge to ArtifactHub for repo
- [x] Add official badge to ArtifactHub
- [x] Reference chart on Kepler docs repo
- [x] Add Maintainer's emails/names as owners to this org
- [ ] Write blog

**Comment by bradmccoydev** [comment]
I have created an issue that depends on this being finished which relates to adding secrets in the repo so I can sign the helm chart.  Signing the helm chart does not change how users use it today it just gives them the additional option of verifying the signature is good and the package hasn't been altered. https://github.com/sustainable-computing-io/kepler-helm-chart/issues/23

**Comment by bradmccoydev** [comment]
We are now signed, verified, and official on ArtifactHub. I have also made a small blog and hopefully will be published in the next eBPF newsletter by Bill Mulligan

**Comment by rootfs** [comment]
@bradmccoydev Thanks for the great work!
